version: '2'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "8081:80"
    volumes:
      - /var/certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /etc/nginx/vhost.d \
      - /usr/share/nginx/html \
    lable: com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
  whoami:
    image: jwilder/whoami
    environment:
      - VIRTUAL_HOST=whoami.local
  iroam:
    build: ./app/
    environment:
      - VIRTUAL_HOST=embed.iroam.local
    
version: "2"

services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/etc/nginx/conf.d"
      - "/etc/nginx/vhost.d"
      - "/usr/share/nginx/html"
      - "../../../volumes/proxy/certs:/etc/nginx/certs:ro"
    networks:
      - proxy-tier
  nginx-gen:
    image: jwilder/docker-gen
    container_name: nginx-gen
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "../../../volumes/proxy/templates/nginx-compose-v2.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro"
    volumes_from:
      - nginx
    entrypoint: /usr/local/bin/docker-gen -notify-sighup nginx -watch -only-exposed -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-nginx-proxy-companion
    volumes_from:
      - nginx
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "../../../volumes/proxy/certs:/etc/nginx/certs:rw"
    environment:
      - NGINX_DOCKER_GEN_CONTAINER=nginx-gen

  embed
    build: ./app/
    environment:
      - VIRTUAL_HOST=test.maxc.in
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=test.maxc.in
      - LETSENCRYPT_EMAIL=maxc@maxc.in
    networks:
      - proxy-tier

networks:
  proxy-tier:
    external:
      name: nginx-proxy