version: "2"

services:
  nginx-proxy:
    image: 'jwilder/nginx-proxy:latest'
    ports:
      - '8080:80'
    volumes:
      - '/var/run/docker.sock:/tmp/docker.sock:ro'
      - /usr/share/nginx/html
      - /etc/nginx/vhost.d
  app:
    build: ./app/
    environment:
      - VIRTUAL_HOST=app.ac.local
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=app.ac.local
      - LETSENCRYPT_EMAIL=maxc@maxc.in
  embed:
    build: ./embed/
    environment:
      - VIRTUAL_HOST=embed.ac.local
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=embed.ac.local
      - LETSENCRYPT_EMAIL=maxc@maxc.in