version: "2"

services:
  nginx:
    image: jwilder/nginx-proxy
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/etc/nginx/conf.d"
      - "/etc/nginx/vhost.d"
      - "/usr/share/nginx/html"
      - "./proxy/certs:/etc/nginx/certs:rw"
  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-nginx-proxy-companion
    volumes_from:
      - nginx
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
  embed:
    build: ./embed/
    environment:
      - VIRTUAL_HOST=test1.maxc.in
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=test1.maxc.in
      - LETSENCRYPT_EMAIL=maxc@maxc.in